CREATE DATABASE NetConf2021
GO

USE NetConf2021
GO

CREATE TABLE [dbo].[Tiendas](
	[ID] [int] NOT NULL,
	[TIENDA] [varchar](50) NOT NULL,
	[DIRECCION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Tiendas] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Articulos](
	[ID] [int] NOT NULL,
	[EAN] [bigint] NOT NULL,
	[DESCRIPCION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Articulos] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[EAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VentasTiendas](
	[FECHA] [varchar](8) NOT NULL,
	[TIENDA] [int] NOT NULL,
	[ARTICULO] [int] NOT NULL,
	[VENTA] [int] NOT NULL,
 CONSTRAINT [PK_VentasTiendas] PRIMARY KEY CLUSTERED 
(
	[FECHA] ASC,
	[TIENDA] ASC,
	[ARTICULO] ASC,
	[VENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


